### ISSUE TITLE
Updating result_table inside a loop

### ISSUE THREAD

**Issue by Gautamshahi** [SuLab/sparql_to_pandas#2]
Hi,

I am trying to the values for multiple SPARQL queries and I wanted to store the result in each row, but I am not able to get it on the result_table. 

My code is 

{'Bremen': 'http://dbpedia.org/resource/Bremen', 'Berlin': 'http://dbpedia.org/resource/Berlin'}

sparql_service_url = "http://dbpedia.org/sparql"
for key, value in keywords.items():
    sparql_query = """SELECT ?uri ?area ?population
 WHERE {
     ?uri <http://dbpedia.org/ontology/areaTotal> ?area.
      ?uri <http://dbpedia.org/ontology/populationMetro> ?population.
 FILTER (?uri = <""" + value + """>) }
    """
    result_table = query_dbpedia(sparql_query, sparql_service_url)

How can I update the result_table?

**Comment by veleritas** [comment]
Hi,

The function for converting SPARQL to Pandas only works for a single query. You can append the individual query results together into a single dataframe if you prefer.

Also, your SPARQL query is incorrectly formatted.

You can get the results for all cities with:

```
query = """select distinct ?city ?area ?population where {
  ?city dbo:populationMetro ?population.
  ?city dbo:areaMetro ?area.
}
"""

url = "http://dbpedia-live.openlinksw.com/sparql"

results = query_dbpedia(query, url)
```

Or you can get the result for a single city with:

```
select distinct ?city ?area ?population where {
  bind(dbr:Bremen as ?city).
  ?city dbo:populationMetro ?population.
  ?city dbo:areaMetro ?area.
}
```
